apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-imported-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100G
  storageClassName: scw-fs
  volumeName: test-pv
